"""add_chunk_indexing_status

Revision ID: 220e9c560b57
Revises: 20241201_0001
Create Date: 2025-12-02 14:50:28.357523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '220e9c560b57'
down_revision: Union[str, None] = '20241201_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'prefix',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    
    # 先添加可空列，设置默认值，再改为 NOT NULL
    op.add_column('chunks', sa.Column('indexing_status', sa.String(length=20), nullable=True))
    op.add_column('chunks', sa.Column('indexing_error', sa.Text(), nullable=True))
    op.add_column('chunks', sa.Column('indexing_retry_count', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('enriched_text', sa.Text(), nullable=True))
    op.add_column('chunks', sa.Column('enrichment_status', sa.String(length=20), nullable=True))
    
    # 为现有数据设置默认值
    op.execute("UPDATE chunks SET indexing_status = 'indexed' WHERE indexing_status IS NULL")
    op.execute("UPDATE chunks SET indexing_retry_count = 0 WHERE indexing_retry_count IS NULL")
    
    # 再改为 NOT NULL
    op.alter_column('chunks', 'indexing_status', nullable=False)
    op.alter_column('chunks', 'indexing_retry_count', nullable=False)
    
    op.create_index(op.f('ix_chunks_indexing_status'), 'chunks', ['indexing_status'], unique=False)
    op.add_column('documents', sa.Column('summary', sa.String(length=2000), nullable=True))
    op.add_column('documents', sa.Column('summary_status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_knowledge_bases_tenant_id'), 'knowledge_bases', ['tenant_id'], unique=False)
    op.alter_column('users', 'roles',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.alter_column('users', 'roles',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_knowledge_bases_tenant_id'), table_name='knowledge_bases')
    op.drop_column('documents', 'summary_status')
    op.drop_column('documents', 'summary')
    op.drop_index(op.f('ix_chunks_indexing_status'), table_name='chunks')
    op.drop_column('chunks', 'enrichment_status')
    op.drop_column('chunks', 'enriched_text')
    op.drop_column('chunks', 'indexing_retry_count')
    op.drop_column('chunks', 'indexing_error')
    op.drop_column('chunks', 'indexing_status')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.alter_column('api_keys', 'prefix',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###
