"""add tenant management fields

Revision ID: 4bfb74f0f2d5
Revises: 220e9c560b57
Create Date: 2025-12-03 06:45:51.747140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfb74f0f2d5'
down_revision: Union[str, None] = '220e9c560b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # api_keys 表新增字段（带默认值以支持现有数据）
    op.add_column('api_keys', sa.Column('role', sa.String(length=20), nullable=False, server_default='write'))
    op.add_column('api_keys', sa.Column('scope_kb_ids', sa.JSON(), nullable=True))
    op.add_column('api_keys', sa.Column('is_initial', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('api_keys', sa.Column('description', sa.Text(), nullable=True))
    
    # tenants 表新增字段（带默认值以支持现有数据）
    op.add_column('tenants', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    op.add_column('tenants', sa.Column('quota_kb_count', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('tenants', sa.Column('quota_doc_count', sa.Integer(), nullable=False, server_default='1000'))
    op.add_column('tenants', sa.Column('quota_storage_mb', sa.Integer(), nullable=False, server_default='1024'))
    op.add_column('tenants', sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('disabled_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    
    # 创建 usage_logs 表
    op.create_table('usage_logs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('tenant_id', sa.String(length=36), nullable=False),
        sa.Column('api_key_id', sa.String(length=36), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('resource_type', sa.String(length=50), nullable=True),
        sa.Column('resource_id', sa.String(length=36), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_action'), 'usage_logs', ['action'], unique=False)
    op.create_index(op.f('ix_usage_logs_api_key_id'), 'usage_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_created_at'), 'usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_tenant_id'), 'usage_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除 usage_logs 表
    op.drop_index(op.f('ix_usage_logs_tenant_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_created_at'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_api_key_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_action'), table_name='usage_logs')
    op.drop_table('usage_logs')
    
    # 删除 tenants 表新增字段
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_column('tenants', 'disabled_reason')
    op.drop_column('tenants', 'disabled_at')
    op.drop_column('tenants', 'quota_storage_mb')
    op.drop_column('tenants', 'quota_doc_count')
    op.drop_column('tenants', 'quota_kb_count')
    op.drop_column('tenants', 'status')
    
    # 删除 api_keys 表新增字段
    op.drop_column('api_keys', 'description')
    op.drop_column('api_keys', 'is_initial')
    op.drop_column('api_keys', 'scope_kb_ids')
    op.drop_column('api_keys', 'role')
    # ### end Alembic commands ###
