"""add_apikey_identity_field

Revision ID: a03b985e8e23
Revises: ea763878e44f
Create Date: 2025-12-04 11:48:34.881532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03b985e8e23'
down_revision: Union[str, None] = 'ea763878e44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('identity', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'identity')
    # ### end Alembic commands ###
