"""add document acl fields

Revision ID: ea763878e44f
Revises: 7c2149e9b995
Create Date: 2025-12-04 11:22:06.436724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea763878e44f'
down_revision: Union[str, None] = '7c2149e9b995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('sensitivity_level', sa.String(length=20), nullable=False, server_default='internal'))
    op.add_column('documents', sa.Column('acl_users', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('acl_roles', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('acl_groups', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_documents_sensitivity_level'), 'documents', ['sensitivity_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_sensitivity_level'), table_name='documents')
    op.drop_column('documents', 'acl_groups')
    op.drop_column('documents', 'acl_roles')
    op.drop_column('documents', 'acl_users')
    op.drop_column('documents', 'sensitivity_level')
    # ### end Alembic commands ###
