"""split_drug_projects_table

Revision ID: 3ea2280278f3
Revises: ffcd18cedb60
Create Date: 2026-03-12 13:49:16.204776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ea2280278f3'
down_revision: Union[str, None] = 'ffcd18cedb60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_dict',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('standard_name', sa.String(length=200), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('moa_default', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_dict_standard_name'), 'target_dict', ['standard_name'], unique=False)
    op.create_table('project_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('indication', sa.String(length=255), nullable=True),
    sa.Column('dev_phase', sa.Enum('PRE_CLINICAL', 'PHASE_I', 'PHASE_II', 'PHASE_III', 'NDA', 'APPROVED', name='devphaseenum'), nullable=True),
    sa.Column('overall_status', sa.Enum('SCREENING', 'IN_PROGRESS', 'ARCHIVED', 'MONITORING', 'RESTARTED', name='overallstatusenum'), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['target_dict.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_master_dev_phase'), 'project_master', ['dev_phase'], unique=False)
    op.create_index(op.f('ix_project_master_drug_name'), 'project_master', ['drug_name'], unique=False)
    op.create_index(op.f('ix_project_master_indication'), 'project_master', ['indication'], unique=False)
    op.create_index(op.f('ix_project_master_is_deleted'), 'project_master', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_project_master_overall_score'), 'project_master', ['overall_score'], unique=False)
    op.create_index(op.f('ix_project_master_overall_status'), 'project_master', ['overall_status'], unique=False)
    op.create_index(op.f('ix_project_master_target_id'), 'project_master', ['target_id'], unique=False)
    op.create_table('project_details',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('drug_type', sa.String(length=100), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('project_highlights', sa.Text(), nullable=True),
    sa.Column('differentiation', sa.Text(), nullable=True),
    sa.Column('efficacy_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_therapy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_institution_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('role_type', sa.Enum('ORIGINATOR', 'CO_DEVELOPER', 'INVESTOR', name='institutionroleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_institution_links_institution_id'), 'project_institution_links', ['institution_id'], unique=False)
    op.create_index(op.f('ix_project_institution_links_project_id'), 'project_institution_links', ['project_id'], unique=False)
    op.create_table('project_management_info',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_leader_id', sa.String(length=36), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_records', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_leader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_project_management_info_project_leader_id'), 'project_management_info', ['project_leader_id'], unique=False)
    op.create_table('project_valuations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('project_valuation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('company_valuation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('strategic_fit_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('valuation_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_valuations_project_id'), 'project_valuations', ['project_id'], unique=False)
    op.create_table('research_details',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('market_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_mech', sa.Text(), nullable=True),
    sa.Column('competitor_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patent_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_impact', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.drop_index(op.f('idx_drug_projects_dosage_form'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_drug_type'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_indication'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_indication_type'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_is_deleted'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_overall_score'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_project_name'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_research_institution'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_research_stage'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_target'), table_name='drug_projects')
    op.drop_index(op.f('idx_drug_projects_target_type'), table_name='drug_projects')
    op.drop_table('drug_projects')
    op.drop_index(op.f('idx_dict_items_category'), table_name='dict_items')
    op.drop_index(op.f('idx_dict_items_is_active'), table_name='dict_items')
    op.create_index(op.f('ix_dict_items_category'), 'dict_items', ['category'], unique=False)
    op.create_index(op.f('ix_dict_items_is_active'), 'dict_items', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dict_items_is_active'), table_name='dict_items')
    op.drop_index(op.f('ix_dict_items_category'), table_name='dict_items')
    op.create_index(op.f('idx_dict_items_is_active'), 'dict_items', ['is_active'], unique=False)
    op.create_index(op.f('idx_dict_items_category'), 'dict_items', ['category'], unique=False)
    op.create_table('drug_projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('target', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mechanism', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('drug_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dosage_form', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('research_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('indication', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('indication_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('project_highlights', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('differentiation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('efficacy_indicators', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('safety_indicators', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_therapy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('competition_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patent_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patent_layout', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('asking_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('project_valuation', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('company_valuation', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('strategic_fit_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('research_institution', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('project_leader', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('risk_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('preclinical_efficacy_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preclinical_safety_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pharmacokinetics_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('follow_up_person', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('drug_projects_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drug_projects_pkey'))
    )
    op.create_index(op.f('idx_drug_projects_target_type'), 'drug_projects', ['target_type'], unique=False)
    op.create_index(op.f('idx_drug_projects_target'), 'drug_projects', ['target'], unique=False)
    op.create_index(op.f('idx_drug_projects_research_stage'), 'drug_projects', ['research_stage'], unique=False)
    op.create_index(op.f('idx_drug_projects_research_institution'), 'drug_projects', ['research_institution'], unique=False)
    op.create_index(op.f('idx_drug_projects_project_name'), 'drug_projects', ['project_name'], unique=False)
    op.create_index(op.f('idx_drug_projects_overall_score'), 'drug_projects', ['overall_score'], unique=False)
    op.create_index(op.f('idx_drug_projects_is_deleted'), 'drug_projects', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_drug_projects_indication_type'), 'drug_projects', ['indication_type'], unique=False)
    op.create_index(op.f('idx_drug_projects_indication'), 'drug_projects', ['indication'], unique=False)
    op.create_index(op.f('idx_drug_projects_drug_type'), 'drug_projects', ['drug_type'], unique=False)
    op.create_index(op.f('idx_drug_projects_dosage_form'), 'drug_projects', ['dosage_form'], unique=False)
    op.drop_table('research_details')
    op.drop_index(op.f('ix_project_valuations_project_id'), table_name='project_valuations')
    op.drop_table('project_valuations')
    op.drop_index(op.f('ix_project_management_info_project_leader_id'), table_name='project_management_info')
    op.drop_table('project_management_info')
    op.drop_index(op.f('ix_project_institution_links_project_id'), table_name='project_institution_links')
    op.drop_index(op.f('ix_project_institution_links_institution_id'), table_name='project_institution_links')
    op.drop_table('project_institution_links')
    op.drop_table('project_details')
    op.drop_index(op.f('ix_project_master_target_id'), table_name='project_master')
    op.drop_index(op.f('ix_project_master_overall_status'), table_name='project_master')
    op.drop_index(op.f('ix_project_master_overall_score'), table_name='project_master')
    op.drop_index(op.f('ix_project_master_is_deleted'), table_name='project_master')
    op.drop_index(op.f('ix_project_master_indication'), table_name='project_master')
    op.drop_index(op.f('ix_project_master_drug_name'), table_name='project_master')
    op.drop_index(op.f('ix_project_master_dev_phase'), table_name='project_master')
    op.drop_table('project_master')
    op.drop_index(op.f('ix_target_dict_standard_name'), table_name='target_dict')
    op.drop_table('target_dict')
    # ### end Alembic commands ###
